"use client"
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "StudyBridge",
  description: "Generated by create next app",
};
import { Inter } from "next/font/google";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

// Ensure correct import path

const inter = Inter({ subsets: ["latin"] });



export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white dark:bg-gray-900 text-black dark:text-white`}  
        >
        {children}
      <body className={inter.className}>
        <div className="flex h-screen bg-gray-100 dark:bg-gray-900">
          {/* Sidebar component */}
          <Sidebar />
          <div className="flex-1 flex flex-col overflow-hidden">
            {/* Header component */}
            <Header />
            {/* Main content */}
            <main className="flex-1 overflow-x-hidden overflow-y-auto bg-gray-100 dark:bg-gray-900">
              {children} {/* This will render the nested page content */}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
