[package]
name = "ipo"
version = "1.0.0"
authors = []

[addresses]
example = "0x3d5B258999DD1f98cD4765E1e69Ae5556cEA6621"

[dev-addresses]

[dependencies]
supra_vrf = { git = "https://github.com/Entropy-Foundation/vrf-interface", subdir = "supra/testnet", rev = "testnet"  }           
       
[dev-dependencies]